// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxmliribskcsxarisqci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4bWxpcmlic2tjc3hhcmlzcWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTExMzMsImV4cCI6MjA2MzEyNzEzM30.5orocgL5-f_yfCSsSHkVgLlEfec9DkjzemJWRJ3yE8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);